[[package]]
url = "https://github.com/akinomyoga/ble.sh/releases/download/nightly/ble-nightly.tar.xz"
type = "tar.xz"
strip-components = 1

remove = [
  "cache.d",
  "doc",
  "run",
]

[package.structure]
"share/blesh" = [ 
  "ble.sh",
  "contrib",
  "keymap",
  "lib"
]
