#!/usr/bin/env bash

name=bzip2
version=1.0.6
url="https://sourceforge.net/projects/bzip2/files/bzip2-${version}.tar.gz/download"
archive_format='gz'

. ./make-steps

package-configure() {
  :
}

package-build() {
  export CFLAGS='-Wall -Winline -O2 -g -fPIC'
  make CFLAGS='-Wall -Winline -O2 -g -fPIC' -j"$(nproc)"
  make CFLAGS='-Wall -Winline -O2 -g -fPIC' -f Makefile-libbz2_so
}

package-install() {
  make install -j"$(nproc)" PREFIX="$install_dir"
  cp -P libbz2.so* "$install_dir"/lib
  ln -sn libbz2.so.1.0 "$install_dir"/lib/libbz2.so

  (
    cd "$install_dir"
    mkdir -p lib/pkgconfig
    cat >>lib/pkgconfig/bzip2.pc <<EOF
prefix="$install_dir"
exec_prefix=\${prefix}
libdir=\${exec_prefix}/lib
includedir=\${prefix}/include

Name: bzip2
Description: A freely available, patent free, high-quality data compressor
Version: ${version}
Libs: -L\${libdir} -lbz2
Cflags: -I\${includedir}
EOF
  )
}

. ./invoke-build
