[[package]]
url = "https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2-linux-x86_64.tar.gz"
type = "tar.gz"
strip-components = 1

[package.structure]
"share/man" = [ "man" ]
"share/doc" = [ "doc" ]
