[[package]]
url="https://github.com/dandavison/delta/releases/download/0.13.0/delta-0.13.0-x86_64-unknown-linux-gnu.tar.gz"
type="tar.gz"
strip-components = 1
output = [
  '*/delta'
]

[package.structure]
bin = [ "delta" ]

