#!/usr/bin/env bash

set -euo pipefail

url="https://github.com/sharkdp/fd/releases/download/v8.3.2/fd-v8.3.2-x86_64-unknown-linux-gnu.tar.gz"
files=(
  '*/fd'
  '*/fd.1'
  '*/autocomplete/fd.bash'
)

if [[ -d /opt/fd ]]; then
  stow --delete --dir=/opt --target=/usr/local fd
  rm -rf /opt/fd
fi

mkdir -p /opt/fd
curl --silent --location "$url" | tar -C /opt/fd -xzf - --strip-components=1 --wildcards "${files[@]}"
mkdir -p /opt/fd/{bin,share/man/man1,completions}
mv /opt/fd/fd /opt/fd/bin
mv /opt/fd/fd.1 /opt/fd/share/man/man1
mv /opt/fd/autocomplete/fd.bash /opt/fd/completions
rm -rf /opt/fd/autocomplete

stow --dir=/opt --target=/usr/local fd
