[[package]]
url = "https://github.com/sharkdp/fd/releases/download/v8.3.2/fd-v8.3.2-x86_64-unknown-linux-gnu.tar.gz"
type = "tar.gz"
strip-components = 1
output = [
  '*/fd',
  '*/fd.1',
  '*/autocomplete/fd.bash'
]

remove = [
  "autocomplete"
]

[package.structure]
bin = [
  "fd"
]
"share/man/man1" = [
  "fd.1"
]
"share/bash-completion/completions" = [
  "autocomplete/fd.bash"
]
