[[package]]
url = "https://github.com/orhun/git-cliff/releases/download/v0.7.0/git-cliff-0.7.0-x86_64-unknown-linux-gnu.tar.gz"
type = "tar.gz"
strip-components = 1
output = [
  "*/completions",
  "*/git-cliff",
  "*/man"
]
remove = [ "man", "completions" ]


[package.structure]
bin = [ "git-cliff" ]
"share/man/man1" = [ "man/git-cliff.1" ]
"share/bash-completion/completions" = [ "completions/git-cliff.bash"]
