#!/usr/bin/env bash

set -euo pipefail

url="https://github.com/jesseduffield/lazygit/releases/download/v0.34/lazygit_0.34_Linux_x86_64.tar.gz"

curl --silent --location "$url" | tar -C /usr/local/bin -xzf- lazygit
