#!/usr/bin/env bash

name=libxslt
url='https://gitlab.gnome.org/GNOME/libxslt/-/archive/v1.1.34/libxslt-v1.1.34.tar.gz'
archive_format=gz

. ./make-steps

package-configure() {
  ACLOCAL_PATH="$LOCAL_OPT/pkg-config/share/aclocal:$LOCAL_OPT/libtool/share/aclocal" ./autogen.sh --prefix="$install_dir"
}

. ./invoke-build
