#!/usr/bin/env bash

set -euo pipefail

package-fetch() {
  local temp_file=$(mktemp)

  if ! [[ -d "$src_dir" ]]; then
    mkdir -p "$src_dir"
  fi

  wget -O "$temp_file" "$url" 1> /dev/null
  tar -xf "$temp_file" -C "$src_dir" --strip-components=1 1>/dev/null

  rm -f "$temp_file"
}

package-configure() {
  ./configure --prefix="$install_dir"
}

package-build() {
  make -j$(nproc)
}

package-install() {
  rm -rf "$install_dir"

  make install -j$(nproc)
}

package-clean() {
  rm -rf "$src_dir"
}

