#!/usr/bin/env bash

set -euo pipefail

src_dir="${src_dir:-$(mktemp -d)}"
install_dir="${install_dir:-/opt/$name}"

package-fetch() {
  if ! [[ -d "$src_dir" ]]; then
    mkdir -p "$src_dir"
  fi
  # shellcheck disable=SC2154
  curl -L -o - "$url" | tar --"${archive_format:-xz}" -xf - -C "$src_dir" --strip-components=1
}

package-change-directory() {
  pushd "$src_dir" 1>/dev/null
}

package-configure() {
  ./configure --prefix="$install_dir"
}

package-build() {
  make -j"$(nproc)"
}

package-clean-links() {
  stow --delete --dir="$install_dir" --target=/usr/local .
  rm -rf "$install_dir"
}

package-install() {
  make install -j"$(nproc)"
}

package-install-links() {
  stow --dir="$install_dir" --target=/usr/local .
}

package-restore-directory() {
  popd 1>/dev/null
}

package-clean() {
  rm -rf "$src_dir"
}

# shellcheck disable=SC2034
steps=(
  fetch
  change-directory
  configure
  build
  clean-links
  install
  install-links
  restore-directory
  clean
)
