#!/usr/bin/env bash

set -euo pipefail

src_dir="${src_dir:-$(mktemp -d)}"
#shellcheck disable=SC2016
if [[ -z ${name:-} ]]; then
  echo "name must be set" >&2
fi
prefix="${PREFIX:-/opt}"
dep=("${dep[@]}")

package-install-dependencies() {
  apt install -y "${dep[@]}"
}

package-fetch() {
  if ! [[ -d "$src_dir" ]]; then
    mkdir -p "$src_dir"
  fi
  # shellcheck disable=SC2154
  curl -L -o - "$url" | tar --"${archive_format:-xz}" -xf - -C "$src_dir" --strip-components=1
}

package-change-directory() {
  pushd "$src_dir" 1>/dev/null
}

package-configure() {
  ./configure --prefix="$prefix/$name"
}

package-build() {
  make -j"$(nproc)"
}

package-clean-links() {
  if [[ ! -d "$prefix/$name" ]]; then
    return
  fi
  stow --delete --dir="$prefix" --target=/usr/local "$name"
  rm -rf "${prefix:?}/$name"
}

package-install() {
  make install -j"$(nproc)"
}

package-install-links() {
  stow --dir="$prefix" --target=/usr/local "$name"
}

package-restore-directory() {
  popd 1>/dev/null
}

package-clean() {
  rm -rf "$src_dir"
}

# shellcheck disable=SC2034
steps=(
  install-dependencies
  fetch
  change-directory
  configure
  build
  clean-links
  install
  install-links
  restore-directory
  clean
)
