#!/usr/bin/env bash

name=neovim
url=https://github.com/neovim/neovim/archive/refs/tags/v0.7.0.tar.gz
archive_format=gz
dep=(ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl doxygen)

. ./make-steps

package-configure() {
  make -j"$(nproc)" CMAKE_INSTALL_PREFIX="$install_dir" CMAKE_BUILD_TYPE=Release
}

. ./invoke-build
