#!/usr/bin/env bash

name=openssl
url='https://www.openssl.org/source/openssl-1.1.1l.tar.gz'
archive_format=gz

. ./make-steps

package-configure() {
  ./config --prefix="$install_dir"
}

. ./invoke-build

