#!/usr/bin/env bash

name='pkg-config'
url='https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz'
archive_format='gz'

. ./make-steps

package-configure() {
  ./configure --with-internal-glib --prefix="$install_dir"
}

. ./invoke-build
