#!/usr/bin/env bash

name=python
url='https://www.python.org/ftp/python/3.10.4/Python-3.10.4.tar.xz'

. ./make-steps

package-configure() {
  ./configure \
    --prefix="$install_dir" \
    --enable-optimizations \
    --enable-loadable-sqlite-extensions \
    CPPFLAGS="$(pkg-config --cflags zlib libffi sqlite3 bzip2)" \
    LDFLAGS="$(pkg-config --libs-only-L zlib libffi sqlite3 bzip2)" \
    LIBS="$(pkg-config --libs-only-l zlib libffi sqlite3 bzip2)"
}

. ./invoke-build
