#!/usr/bin/env bash

set -euo pipefail
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

name=ripgrep
url="https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep-13.0.0-x86_64-unknown-linux-musl.tar.gz"
type=gzip

extract=(
  '*/rg'
  '*/complete/rg.bash'
  '*/doc/rg.1'
)

remove=(
  complete
  doc
)

bin=(rg)
completions=(complete/rg.bash)
man1=(doc/rg.1)

. "$SCRIPT_DIR/tarball-steps"
