[[package]]
url = "https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep-13.0.0-x86_64-unknown-linux-musl.tar.gz"
type="tar.gz"
strip-components = 1
output = [
  "*/rg",
  "*/complete/rg.bash",
  "*/doc/rg.1"
]
remove = [
  "complete",
  "doc"
]

[package.structure]
bin = [
  "rg"
]
"share/bash-completion/completions" = [
  "complete/rg.bash"
]
"share/man/man1" = [
  "doc/rg.1"
]

