[[package]]
url = "https://github.com/koalaman/shellcheck/releases/download/v0.8.0/shellcheck-v0.8.0.linux.x86_64.tar.xz"
type = "tar.xz"
strip-components = 1
output = [ "*/shellcheck" ]

[package.structure]
bin = [ "shellcheck" ]
