#!/usr/bin/env bash

set -euo pipefail

url="https://github.com/koalaman/shellcheck/releases/download/v0.8.0/shellcheck-v0.8.0.linux.x86_64.tar.xz"

curl --silent --location "$url" | tar -C /usr/local/bin -xJf- --wildcards '*shellcheck' --strip-components=1
