#!/usr/bin/env bash

set -euo pipefail

url="https://github.com/starship/starship/releases/download/v1.7.1/starship-x86_64-unknown-linux-gnu.tar.gz"

curl --silent --location "$url" | tar -C /usr/local/bin -xzf-
